"""
NutriHer Nutrition Database Module
===================================
Provides nutritional composition data for 80 Indian food classes.
Values are referenced against the Indian Food Composition Tables (IFCT 2017)
published by the National Institute of Nutrition (NIN) / Indian Council of
Medical Research (ICMR).

Academic Transparency Note:
- Direct items (e.g., Chapati, Chaas) map to direct IFCT 2017 food entries.
- Composite dishes (e.g., Biryani, Pongal, Palak Paneer) use standardized
  recipe proportions computed from raw IFCT 2017 ingredient entries.
- All values are per 100g edible portion.
"""

from typing import Dict, Any, Optional

NUTRITION_DATABASE: Dict[str, Dict[str, Any]] = {
    "aloo gobi": {
        "food_name": "Aloo Gobi",
        "iron_mg_per_100g": 1.6,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 28.0,
        "calcium_mg_per_100g": 34.0,
        "protein_g_per_100g": 3.4,
        "energy_kcal_per_100g": 140.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Potato and cauliflower curry; high vitamin C from cauliflower enhances non-heme iron.",
    },
    "aloo methi": {
        "food_name": "Aloo Methi",
        "iron_mg_per_100g": 3.2,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 32.0,
        "calcium_mg_per_100g": 115.0,
        "protein_g_per_100g": 3.8,
        "energy_kcal_per_100g": 135.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Fenugreek leaves contribute significant non-heme iron and vitamin C.",
    },
    "aloo mutter": {
        "food_name": "Aloo Mutter",
        "iron_mg_per_100g": 1.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 18.0,
        "calcium_mg_per_100g": 30.0,
        "protein_g_per_100g": 4.5,
        "energy_kcal_per_100g": 145.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Green peas and potatoes in spiced tomato-onion gravy.",
    },
    "aloo paratha": {
        "food_name": "Aloo Paratha",
        "iron_mg_per_100g": 2.1,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 4.0,
        "calcium_mg_per_100g": 28.0,
        "protein_g_per_100g": 5.5,
        "energy_kcal_per_100g": 260.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Whole wheat flatbread stuffed with spiced mashed potatoes and cooked in oil/ghee.",
    },
    "amritsari kulcha": {
        "food_name": "Amritsari Kulcha",
        "iron_mg_per_100g": 1.7,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 2.0,
        "calcium_mg_per_100g": 25.0,
        "protein_g_per_100g": 6.0,
        "energy_kcal_per_100g": 285.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Refined flour leavened bread stuffed with spiced potatoes and onions, baked in tandoor.",
    },
    "anda curry": {
        "food_name": "Anda Curry",
        "iron_mg_per_100g": 2.2,
        "iron_type": "heme",
        "vitamin_c_mg_per_100g": 6.0,
        "calcium_mg_per_100g": 50.0,
        "protein_g_per_100g": 11.5,
        "energy_kcal_per_100g": 175.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Hard-boiled eggs in onion-tomato gravy. Contains bioavailable egg iron.",
    },
    "balushahi": {
        "food_name": "Balushahi",
        "iron_mg_per_100g": 0.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 15.0,
        "protein_g_per_100g": 3.8,
        "energy_kcal_per_100g": 420.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Deep fried maida pastry soaked in sugar syrup; low micronutrient density.",
    },
    "banana chips": {
        "food_name": "Banana Chips",
        "iron_mg_per_100g": 1.2,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 1.5,
        "calcium_mg_per_100g": 18.0,
        "protein_g_per_100g": 2.3,
        "energy_kcal_per_100g": 519.0,
        "source_type": "IFCT 2017 Direct",
        "notes": "Raw plantain sliced and fried in coconut/vegetable oil with salt and spices.",
    },
    "besan laddu": {
        "food_name": "Besan Laddu",
        "iron_mg_per_100g": 3.5,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 45.0,
        "protein_g_per_100g": 9.2,
        "energy_kcal_per_100g": 480.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Gram flour (chana dal flour) roasted in ghee with sugar; high non-heme iron from chickpea base.",
    },
    "bhindi masala": {
        "food_name": "Bhindi Masala",
        "iron_mg_per_100g": 1.5,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 21.0,
        "calcium_mg_per_100g": 86.0,
        "protein_g_per_100g": 2.5,
        "energy_kcal_per_100g": 110.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Okra sautéed with onions, tomatoes, and spices. Good source of dietary fiber and vitamin C.",
    },
    "biryani": {
        "food_name": "Biryani",
        "iron_mg_per_100g": 2.1,
        "iron_type": "heme",
        "vitamin_c_mg_per_100g": 3.0,
        "calcium_mg_per_100g": 28.0,
        "protein_g_per_100g": 8.0,
        "energy_kcal_per_100g": 260.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Spiced rice layered with chicken/vegetables, herbs, and aromatics.",
    },
    "boondi laddu": {
        "food_name": "Boondi Laddu",
        "iron_mg_per_100g": 2.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 35.0,
        "protein_g_per_100g": 6.5,
        "energy_kcal_per_100g": 450.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Deep-fried gram flour pearls steeped in sugar syrup with cardamom and nuts.",
    },
    "chaas": {
        "food_name": "Chaas",
        "iron_mg_per_100g": 0.1,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 1.0,
        "calcium_mg_per_100g": 95.0,
        "protein_g_per_100g": 1.6,
        "energy_kcal_per_100g": 35.0,
        "source_type": "IFCT 2017 Direct",
        "notes": "Spiced diluted yogurt / buttermilk. High calcium may moderate non-heme iron absorption.",
    },
    "chana masala": {
        "food_name": "Chana Masala",
        "iron_mg_per_100g": 3.4,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 12.0,
        "calcium_mg_per_100g": 65.0,
        "protein_g_per_100g": 8.5,
        "energy_kcal_per_100g": 165.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Chickpea curry in spiced tomato-onion gravy; rich in non-heme iron and dietary fiber.",
    },
    "chapati": {
        "food_name": "Chapati",
        "iron_mg_per_100g": 3.1,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 30.0,
        "protein_g_per_100g": 9.4,
        "energy_kcal_per_100g": 275.0,
        "source_type": "IFCT 2017 Direct",
        "notes": "Unleavened whole wheat flatbread baked on tawa; whole grain iron with natural phytates.",
    },
    "chicken pizza": {
        "food_name": "Chicken Pizza",
        "iron_mg_per_100g": 1.9,
        "iron_type": "heme",
        "vitamin_c_mg_per_100g": 5.0,
        "calcium_mg_per_100g": 140.0,
        "protein_g_per_100g": 12.0,
        "energy_kcal_per_100g": 265.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Crust topped with chicken, cheese, and tomato sauce; combines heme and dairy calcium.",
    },
    "chicken wings": {
        "food_name": "Chicken Wings",
        "iron_mg_per_100g": 1.5,
        "iron_type": "heme",
        "vitamin_c_mg_per_100g": 0.5,
        "calcium_mg_per_100g": 15.0,
        "protein_g_per_100g": 18.5,
        "energy_kcal_per_100g": 290.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Roasted/fried chicken wings; high heme iron bioavailability.",
    },
    "chikki": {
        "food_name": "Chikki",
        "iron_mg_per_100g": 3.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 75.0,
        "protein_g_per_100g": 11.0,
        "energy_kcal_per_100g": 485.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Peanut and jaggery brittle; jaggery and peanuts together provide valuable plant iron.",
    },
    "chivda": {
        "food_name": "Chivda",
        "iron_mg_per_100g": 4.2,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.5,
        "calcium_mg_per_100g": 40.0,
        "protein_g_per_100g": 6.8,
        "energy_kcal_per_100g": 460.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Roasted flattened rice snack with peanuts and curry leaves; naturally iron-rich flattened rice base.",
    },
    "chole bhature": {
        "food_name": "Chole Bhature",
        "iron_mg_per_100g": 2.6,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 6.0,
        "calcium_mg_per_100g": 45.0,
        "protein_g_per_100g": 7.5,
        "energy_kcal_per_100g": 295.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Spiced chickpea curry served with deep-fried leavened sourdough bread.",
    },
    "dabeli": {
        "food_name": "Dabeli",
        "iron_mg_per_100g": 1.9,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 7.0,
        "calcium_mg_per_100g": 35.0,
        "protein_g_per_100g": 5.2,
        "energy_kcal_per_100g": 240.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Spiced potato mix in burger bun with tamarind/date chutney and pomegranate seeds.",
    },
    "dal khichdi": {
        "food_name": "Dal Khichdi",
        "iron_mg_per_100g": 1.9,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 2.0,
        "calcium_mg_per_100g": 32.0,
        "protein_g_per_100g": 6.2,
        "energy_kcal_per_100g": 160.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Moong dal and rice cooked together with mild turmeric and cumin tempering.",
    },
    "dhokla": {
        "food_name": "Dhokla",
        "iron_mg_per_100g": 1.7,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 4.0,
        "calcium_mg_per_100g": 28.0,
        "protein_g_per_100g": 5.8,
        "energy_kcal_per_100g": 152.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Fermented gram flour / pulse batter steamed with green chili and mustard seed tempering.",
    },
    "falooda": {
        "food_name": "Falooda",
        "iron_mg_per_100g": 0.6,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 1.0,
        "calcium_mg_per_100g": 110.0,
        "protein_g_per_100g": 3.2,
        "energy_kcal_per_100g": 190.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Layered dessert drink with milk, vermicelli, basil seeds (sabja), rose syrup, and ice cream.",
    },
    "fish curry": {
        "food_name": "Fish Curry",
        "iron_mg_per_100g": 2.4,
        "iron_type": "heme",
        "vitamin_c_mg_per_100g": 8.0,
        "calcium_mg_per_100g": 42.0,
        "protein_g_per_100g": 14.5,
        "energy_kcal_per_100g": 155.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Fish simmered in coconut/tamarind gravy; rich in highly bioavailable heme iron.",
    },
    "gajar ka halwa": {
        "food_name": "Gajar Ka Halwa",
        "iron_mg_per_100g": 1.2,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 3.0,
        "calcium_mg_per_100g": 90.0,
        "protein_g_per_100g": 4.1,
        "energy_kcal_per_100g": 260.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Grated carrots simmered in milk, ghee, cardamom, and nuts.",
    },
    "garlic bread": {
        "food_name": "Garlic Bread",
        "iron_mg_per_100g": 1.4,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 1.0,
        "calcium_mg_per_100g": 45.0,
        "protein_g_per_100g": 7.0,
        "energy_kcal_per_100g": 320.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Baguette/bread slices toasted with garlic butter and herbs.",
    },
    "garlic naan": {
        "food_name": "Garlic Naan",
        "iron_mg_per_100g": 1.6,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 1.5,
        "calcium_mg_per_100g": 35.0,
        "protein_g_per_100g": 7.5,
        "energy_kcal_per_100g": 290.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Tandoor baked refined flour flatbread brushed with garlic butter.",
    },
    "ghevar": {
        "food_name": "Ghevar",
        "iron_mg_per_100g": 0.9,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 30.0,
        "protein_g_per_100g": 4.0,
        "energy_kcal_per_100g": 460.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Traditional Rajasthani disc-shaped honeycomb sweet soaked in sugar syrup.",
    },
    "grilled sandwich": {
        "food_name": "Grilled Sandwich",
        "iron_mg_per_100g": 1.7,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 9.0,
        "calcium_mg_per_100g": 70.0,
        "protein_g_per_100g": 6.5,
        "energy_kcal_per_100g": 235.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Toasted bread with vegetable stuffing (capsicum, tomato, potato) and green chutney.",
    },
    "gujhia": {
        "food_name": "Gujhia",
        "iron_mg_per_100g": 1.3,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 65.0,
        "protein_g_per_100g": 6.0,
        "energy_kcal_per_100g": 430.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Deep fried dumpling stuffed with sweetened mawa (khoya) and dried fruits.",
    },
    "gulab jamun": {
        "food_name": "Gulab Jamun",
        "iron_mg_per_100g": 0.7,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 85.0,
        "protein_g_per_100g": 4.5,
        "energy_kcal_per_100g": 325.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Deep fried milk solid balls soaked in rose-flavored sugar syrup.",
    },
    "hara bhara kabab": {
        "food_name": "Hara Bhara Kabab",
        "iron_mg_per_100g": 3.6,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 26.0,
        "calcium_mg_per_100g": 95.0,
        "protein_g_per_100g": 6.8,
        "energy_kcal_per_100g": 180.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Spinach, green pea, and potato patties; high non-heme iron and vitamin C combination.",
    },
    "idiyappam": {
        "food_name": "Idiyappam",
        "iron_mg_per_100g": 0.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 12.0,
        "protein_g_per_100g": 2.8,
        "energy_kcal_per_100g": 130.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Steamed rice flour string hoppers; light and easily digestible staple.",
    },
    "idli": {
        "food_name": "Idli",
        "iron_mg_per_100g": 0.9,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 18.0,
        "protein_g_per_100g": 4.0,
        "energy_kcal_per_100g": 132.0,
        "source_type": "IFCT 2017 Direct",
        "notes": "Steamed fermented rice and black gram cake. Fermentation lowers phytates slightly.",
    },
    "jalebi": {
        "food_name": "Jalebi",
        "iron_mg_per_100g": 0.6,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 12.0,
        "protein_g_per_100g": 2.1,
        "energy_kcal_per_100g": 380.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Fermented batter fried into pretzel spirals and soaked in saffron syrup.",
    },
    "kaju katli": {
        "food_name": "Kaju Katli",
        "iron_mg_per_100g": 2.5,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 38.0,
        "protein_g_per_100g": 8.5,
        "energy_kcal_per_100g": 470.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Cashew nut fudge; cashews naturally provide non-heme iron and magnesium.",
    },
    "khakhra": {
        "food_name": "Khakhra",
        "iron_mg_per_100g": 3.4,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.5,
        "calcium_mg_per_100g": 35.0,
        "protein_g_per_100g": 9.5,
        "energy_kcal_per_100g": 410.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Crisp whole wheat roasted flatbread spiced with cumin, turmeric, or fenugreek.",
    },
    "kheer": {
        "food_name": "Kheer",
        "iron_mg_per_100g": 0.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.5,
        "calcium_mg_per_100g": 120.0,
        "protein_g_per_100g": 4.2,
        "energy_kcal_per_100g": 165.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Rice pudding simmered with milk, cardamom, saffron, and nuts.",
    },
    "kulfi": {
        "food_name": "Kulfi",
        "iron_mg_per_100g": 0.5,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 160.0,
        "protein_g_per_100g": 5.8,
        "energy_kcal_per_100g": 240.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Traditional dense frozen dairy dessert flavoured with cardamom and pistachios.",
    },
    "margherita pizza": {
        "food_name": "Margherita Pizza",
        "iron_mg_per_100g": 1.5,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 6.5,
        "calcium_mg_per_100g": 160.0,
        "protein_g_per_100g": 9.5,
        "energy_kcal_per_100g": 250.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Pizza dough with mozzarella cheese and tomato passata.",
    },
    "masala dosa": {
        "food_name": "Masala Dosa",
        "iron_mg_per_100g": 1.4,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 6.0,
        "calcium_mg_per_100g": 30.0,
        "protein_g_per_100g": 5.2,
        "energy_kcal_per_100g": 210.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Crisp fermented rice-lentil crepe filled with spiced onion-potato masala.",
    },
    "masala papad": {
        "food_name": "Masala Papad",
        "iron_mg_per_100g": 2.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 15.0,
        "calcium_mg_per_100g": 55.0,
        "protein_g_per_100g": 7.0,
        "energy_kcal_per_100g": 195.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Roasted pulse wafer topped with diced onions, tomatoes, coriander, and lemon juice.",
    },
    "medu vada": {
        "food_name": "Medu Vada",
        "iron_mg_per_100g": 2.3,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 1.0,
        "calcium_mg_per_100g": 40.0,
        "protein_g_per_100g": 7.5,
        "energy_kcal_per_100g": 275.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Deep-fried doughnut-shaped black gram (urad dal) fritters with peppercorns and curry leaves.",
    },
    "misal pav": {
        "food_name": "Misal Pav",
        "iron_mg_per_100g": 3.1,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 14.0,
        "calcium_mg_per_100g": 50.0,
        "protein_g_per_100g": 7.8,
        "energy_kcal_per_100g": 220.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Sprouted moth bean curry topped with farsan, onions, lemon juice, served with pav.",
    },
    "modak": {
        "food_name": "Modak",
        "iron_mg_per_100g": 1.5,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.5,
        "calcium_mg_per_100g": 32.0,
        "protein_g_per_100g": 3.2,
        "energy_kcal_per_100g": 240.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Steamed rice flour dumplings filled with freshly grated coconut and jaggery.",
    },
    "moong dal halwa": {
        "food_name": "Moong Dal Halwa",
        "iron_mg_per_100g": 2.7,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 48.0,
        "protein_g_per_100g": 7.8,
        "energy_kcal_per_100g": 410.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Yellow moong lentil paste slow-cooked in ghee, milk, and sugar.",
    },
    "murukku": {
        "food_name": "Murukku",
        "iron_mg_per_100g": 2.0,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 35.0,
        "protein_g_per_100g": 6.2,
        "energy_kcal_per_100g": 510.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Spiral crunchy snack made from rice flour and urad dal flour seasoned with sesame/cumin.",
    },
    "mysore pak": {
        "food_name": "Mysore Pak",
        "iron_mg_per_100g": 1.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 25.0,
        "protein_g_per_100g": 5.5,
        "energy_kcal_per_100g": 540.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Traditional sweet prepared with gram flour, generous amounts of ghee, and sugar.",
    },
    "navratan korma": {
        "food_name": "Navratan Korma",
        "iron_mg_per_100g": 1.9,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 12.0,
        "calcium_mg_per_100g": 75.0,
        "protein_g_per_100g": 5.4,
        "energy_kcal_per_100g": 210.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Mughlai dish made with mixed vegetables, paneer, and cashew-cream gravy.",
    },
    "neer dosa": {
        "food_name": "Neer Dosa",
        "iron_mg_per_100g": 0.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 10.0,
        "protein_g_per_100g": 2.5,
        "energy_kcal_per_100g": 125.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Delicate, soft South Indian crepe prepared from unfermented watery rice batter.",
    },
    "onion pakoda": {
        "food_name": "Onion Pakoda",
        "iron_mg_per_100g": 2.4,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 6.0,
        "calcium_mg_per_100g": 42.0,
        "protein_g_per_100g": 5.9,
        "energy_kcal_per_100g": 315.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Sliced onions coated in seasoned gram flour batter and deep fried.",
    },
    "palak paneer": {
        "food_name": "Palak Paneer",
        "iron_mg_per_100g": 3.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 22.0,
        "calcium_mg_per_100g": 210.0,
        "protein_g_per_100g": 10.2,
        "energy_kcal_per_100g": 205.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Blanched spinach puree cooked with Indian cottage cheese (paneer) and spices.",
    },
    "paneer masala": {
        "food_name": "Paneer Masala",
        "iron_mg_per_100g": 2.1,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 11.0,
        "calcium_mg_per_100g": 190.0,
        "protein_g_per_100g": 11.5,
        "energy_kcal_per_100g": 235.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Paneer cubes simmered in spiced tomato and onion gravy.",
    },
    "paneer pizza": {
        "food_name": "Paneer Pizza",
        "iron_mg_per_100g": 1.7,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 7.0,
        "calcium_mg_per_100g": 175.0,
        "protein_g_per_100g": 10.5,
        "energy_kcal_per_100g": 255.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Pizza topped with marinated paneer, bell peppers, mozzarella, and tomato sauce.",
    },
    "pani puri": {
        "food_name": "Pani Puri",
        "iron_mg_per_100g": 1.6,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 8.5,
        "calcium_mg_per_100g": 24.0,
        "protein_g_per_100g": 3.5,
        "energy_kcal_per_100g": 160.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Hollow fried puris filled with potato/chickpea mixture and mint-coriander-tamarind water.",
    },
    "paniyaram": {
        "food_name": "Paniyaram",
        "iron_mg_per_100g": 1.2,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 3.0,
        "calcium_mg_per_100g": 22.0,
        "protein_g_per_100g": 4.6,
        "energy_kcal_per_100g": 165.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Dumplings made from seasoned fermented idli/dosa batter cooked in special appe mould.",
    },
    "papdi chaat": {
        "food_name": "Papdi Chaat",
        "iron_mg_per_100g": 2.0,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 6.5,
        "calcium_mg_per_100g": 75.0,
        "protein_g_per_100g": 5.4,
        "energy_kcal_per_100g": 215.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Crisp papdis topped with boiled potatoes, chickpeas, sweetened curd, tamarind and mint chutneys.",
    },
    "patrode": {
        "food_name": "Patrode",
        "iron_mg_per_100g": 4.5,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 35.0,
        "calcium_mg_per_100g": 140.0,
        "protein_g_per_100g": 6.2,
        "energy_kcal_per_100g": 165.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Colocasia (taro) leaves smeared with spiced gram flour paste, rolled and steamed; exceptional iron.",
    },
    "pav bhaji": {
        "food_name": "Pav Bhaji",
        "iron_mg_per_100g": 2.4,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 30.0,
        "calcium_mg_per_100g": 60.0,
        "protein_g_per_100g": 5.0,
        "energy_kcal_per_100g": 245.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Mashed mixed vegetables (potatoes, tomatoes, peas, capsicum) with buttered bread roll.",
    },
    "pepperoni pizza": {
        "food_name": "Pepperoni Pizza",
        "iron_mg_per_100g": 2.2,
        "iron_type": "heme",
        "vitamin_c_mg_per_100g": 4.0,
        "calcium_mg_per_100g": 150.0,
        "protein_g_per_100g": 12.5,
        "energy_kcal_per_100g": 280.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Pizza topped with cured meat, mozzarella, and marinara sauce.",
    },
    "phirni": {
        "food_name": "Phirni",
        "iron_mg_per_100g": 0.7,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.5,
        "calcium_mg_per_100g": 115.0,
        "protein_g_per_100g": 4.0,
        "energy_kcal_per_100g": 150.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Slow-cooked ground rice pudding served chilled in earthen pots (matkas).",
    },
    "poha": {
        "food_name": "Poha",
        "iron_mg_per_100g": 1.2,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 12.0,
        "calcium_mg_per_100g": 22.0,
        "protein_g_per_100g": 3.6,
        "energy_kcal_per_100g": 158.0,
        "source_type": "IFCT 2017 Direct",
        "notes": "Flattened rice sautéed with onions, green chilies, mustard seeds, peanuts, and lemon juice.",
    },
    "pongal": {
        "food_name": "Pongal",
        "iron_mg_per_100g": 1.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 2.0,
        "calcium_mg_per_100g": 45.0,
        "protein_g_per_100g": 6.5,
        "energy_kcal_per_100g": 180.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Traditional South Indian dish made from rice and yellow moong dal tempered with cumin, ginger, and black pepper.",
    },
    "puri bhaji": {
        "food_name": "Puri Bhaji",
        "iron_mg_per_100g": 2.2,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 11.0,
        "calcium_mg_per_100g": 32.0,
        "protein_g_per_100g": 4.8,
        "energy_kcal_per_100g": 270.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Deep-fried whole wheat puffed bread served with mildly spiced potato curry.",
    },
    "rajma chawal": {
        "food_name": "Rajma Chawal",
        "iron_mg_per_100g": 3.2,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 5.0,
        "calcium_mg_per_100g": 55.0,
        "protein_g_per_100g": 9.5,
        "energy_kcal_per_100g": 230.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Red kidney bean curry served with steamed basmati rice; excellent plant-based iron.",
    },
    "rasgulla": {
        "food_name": "Rasgulla",
        "iron_mg_per_100g": 0.4,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 0.0,
        "calcium_mg_per_100g": 90.0,
        "protein_g_per_100g": 4.0,
        "energy_kcal_per_100g": 186.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Spongy cottage cheese (chhena) balls boiled in light sugar syrup.",
    },
    "rava dosa": {
        "food_name": "Rava Dosa",
        "iron_mg_per_100g": 1.5,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 2.0,
        "calcium_mg_per_100g": 26.0,
        "protein_g_per_100g": 4.8,
        "energy_kcal_per_100g": 195.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Crisp netted crepe made from semolina (rava), rice flour, and spices.",
    },
    "sabudana khichdi": {
        "food_name": "Sabudana Khichdi",
        "iron_mg_per_100g": 1.4,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 4.0,
        "calcium_mg_per_100g": 20.0,
        "protein_g_per_100g": 4.2,
        "energy_kcal_per_100g": 220.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Tapioca pearls tossed with roasted peanuts, boiled potatoes, and green chilies.",
    },
    "sabudana vada": {
        "food_name": "Sabudana Vada",
        "iron_mg_per_100g": 1.6,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 3.0,
        "calcium_mg_per_100g": 24.0,
        "protein_g_per_100g": 4.8,
        "energy_kcal_per_100g": 280.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Deep fried fritters made of sago pearls, mashed potatoes, and crushed roasted peanuts.",
    },
    "samosa": {
        "food_name": "Samosa",
        "iron_mg_per_100g": 1.1,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 4.0,
        "calcium_mg_per_100g": 20.0,
        "protein_g_per_100g": 3.8,
        "energy_kcal_per_100g": 262.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Crisp pastry pyramid stuffed with spiced potatoes, green peas, and coriander.",
    },
    "seekh kebab": {
        "food_name": "Seekh Kebab",
        "iron_mg_per_100g": 2.8,
        "iron_type": "heme",
        "vitamin_c_mg_per_100g": 3.0,
        "calcium_mg_per_100g": 35.0,
        "protein_g_per_100g": 17.2,
        "energy_kcal_per_100g": 215.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Minced meat seasoned with herbs, ginger, garlic, and grilled on skewers.",
    },
    "set dosa": {
        "food_name": "Set Dosa",
        "iron_mg_per_100g": 1.1,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 1.0,
        "calcium_mg_per_100g": 22.0,
        "protein_g_per_100g": 4.2,
        "energy_kcal_per_100g": 160.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Set of small, spongy, soft fermented rice and flattened rice dosas.",
    },
    "sev puri": {
        "food_name": "Sev Puri",
        "iron_mg_per_100g": 2.2,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 10.0,
        "calcium_mg_per_100g": 42.0,
        "protein_g_per_100g": 5.8,
        "energy_kcal_per_100g": 240.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Crispy flat puris loaded with diced potatoes, onions, chutneys, and crisp chickpea vermicelli (sev).",
    },
    "solkadhi": {
        "food_name": "Solkadhi",
        "iron_mg_per_100g": 0.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 9.0,
        "calcium_mg_per_100g": 40.0,
        "protein_g_per_100g": 1.8,
        "energy_kcal_per_100g": 65.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Konkani digestive drink made from coconut milk and kokum (garcinia indica); high natural acids.",
    },
    "steamed momo": {
        "food_name": "Steamed Momo",
        "iron_mg_per_100g": 1.4,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 4.0,
        "calcium_mg_per_100g": 25.0,
        "protein_g_per_100g": 5.6,
        "energy_kcal_per_100g": 170.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Steamed dough dumplings stuffed with finely minced vegetables, served with spicy chili sauce.",
    },
    "thali": {
        "food_name": "Thali",
        "iron_mg_per_100g": 2.5,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 15.0,
        "calcium_mg_per_100g": 70.0,
        "protein_g_per_100g": 7.2,
        "energy_kcal_per_100g": 195.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Balanced composite platter combining dal, seasonal vegetable sabzi, roti, rice, and salad.",
    },
    "thukpa": {
        "food_name": "Thukpa",
        "iron_mg_per_100g": 1.8,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 14.0,
        "calcium_mg_per_100g": 45.0,
        "protein_g_per_100g": 6.5,
        "energy_kcal_per_100g": 145.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Tibetan noodle soup with mixed vegetables, clear aromatic broth, and herbs.",
    },
    "uttapam": {
        "food_name": "Uttapam",
        "iron_mg_per_100g": 1.3,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 7.0,
        "calcium_mg_per_100g": 28.0,
        "protein_g_per_100g": 4.8,
        "energy_kcal_per_100g": 170.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Thick fermented pancake topped with cooked onions, tomatoes, and green chilies.",
    },
    "vada pav": {
        "food_name": "Vada Pav",
        "iron_mg_per_100g": 2.0,
        "iron_type": "non-heme",
        "vitamin_c_mg_per_100g": 5.0,
        "calcium_mg_per_100g": 35.0,
        "protein_g_per_100g": 5.8,
        "energy_kcal_per_100g": 265.0,
        "source_type": "Composite Recipe Estimation (IFCT 2017 Ingredients)",
        "notes": "Spiced potato batata vada sandwiched in bread roll with garlic and mint chutneys.",
    },
}


def normalize_food_key(name: str) -> str:
    """Normalize input string to match database keys."""
    if not name:
        return "pongal"
    k = name.strip().lower().replace("-", " ").replace("_", " ")
    # Try exact match first
    if k in NUTRITION_DATABASE:
        return k
    # Try underscore form
    k_under = k.replace(" ", "_")
    for key in NUTRITION_DATABASE:
        if key.replace(" ", "_") == k_under or key == k:
            return key
    # Substring match fallback
    for key in NUTRITION_DATABASE:
        if key in k or k in key:
            return key
    return "pongal"


def get_nutrition_data(food_name: str, portion_grams: float = 100.0) -> Dict[str, Any]:
    """
    Retrieve nutritional information for a given food item,
    scaled to the specified portion in grams.
    """
    key = normalize_food_key(food_name)
    base = NUTRITION_DATABASE.get(key, NUTRITION_DATABASE["pongal"])
    try:
        safe_portion = max(0.0, float(portion_grams)) if portion_grams is not None else 100.0
    except (ValueError, TypeError):
        safe_portion = 100.0
    factor = safe_portion / 100.0

    return {
        "food_name": base["food_name"],
        "food_key": key.replace(" ", "_"),
        "label": base["food_name"],
        "portion_g": round(safe_portion, 1),
        "iron": round(base["iron_mg_per_100g"] * factor, 2),
        "iron_mg_per_100g": base["iron_mg_per_100g"],
        "iron_type": base["iron_type"],
        "vitaminC": round(base["vitamin_c_mg_per_100g"] * factor, 1),
        "vitamin_c_mg_per_100g": base["vitamin_c_mg_per_100g"],
        "calcium": round(base["calcium_mg_per_100g"] * factor, 0),
        "calcium_mg_per_100g": base["calcium_mg_per_100g"],
        "protein": round(base["protein_g_per_100g"] * factor, 1),
        "protein_g_per_100g": base["protein_g_per_100g"],
        "energy": round(base["energy_kcal_per_100g"] * factor, 0),
        "energy_kcal_per_100g": base["energy_kcal_per_100g"],
        "source_type": base["source_type"],
        "notes": base["notes"],
    }
